### ISSUE TITLE
Unexpected token with version 1.0.7

### ISSUE THREAD

**Issue by patrikholcak** [ForbesLindesay/acorn-globals#10]
Just `npm install`ed a new [keystone.js](https://github.com/keystonejs/keystone/) project, which has dependency on jade, which has dependency on with, which has dependency on this. After 2 hours of debugging found that v. 1.0.6 works just fine.

```
SyntaxError: Unexpected token (1:216)
  at Parser.pp.raise (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1745:13)
  at Parser.pp.unexpected (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2264:8)
  at Parser.pp.parseBindingAtom (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1876:12)
  at Parser.pp.parseMaybeDefault (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1920:23)
  at Parser.pp.parseBindingList (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1896:23)
  at Parser.pp.parseFunctionParams (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2776:22)
  at Parser.pp.parseFunction (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2769:8)
  at Parser.pp.parseExprAtom (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1129:19)
  at Parser.pp.parseExprSubscripts (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1023:19)
  at Parser.pp.parseMaybeUnary (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1004:19)
  at Parser.pp.parseExprOps (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:948:19)
  at Parser.pp.parseMaybeConditional (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:930:19)
  at Parser.pp.parseMaybeAssign (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:908:19)
  at Parser.pp.parseParenAndDistinguishExpression (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1188:28)
  at Parser.pp.parseExprAtom (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1111:19)
  at Parser.pp.parseExprSubscripts (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1023:19)
  at Parser.pp.parseMaybeUnary (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1004:19)
  at Parser.pp.parseExprOps (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:948:19)
  at Parser.pp.parseMaybeConditional (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:930:19)
  at Parser.pp.parseMaybeAssign (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:908:19)
  at Parser.pp.parseExpression (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:882:19)
  at Parser.pp.parseStatement (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2461:23)
  at Parser.pp.parseTopLevel (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2379:21)
  at Object.parse (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:101:12)
  at reallyParse (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/index.js:24:18)
  at unwrapReturns (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/index.js:90:13)
  at addWith (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/node_modules/with/index.js:77:37)
  at parse (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/lib/index.js:149:9)
  at Object.exports.compile (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/jade/lib/index.js:205:16)
  at compileTemplate (/Users/patrikholcak/dev/test/node_modules/keystone/lib/core/render.js:38:15)
  at [object Object].render (/Users/patrikholcak/dev/test/node_modules/keystone/lib/core/render.js:43:5)
  at module.exports (/Users/patrikholcak/dev/test/node_modules/keystone/admin/routes/views/home.js:5:11)
  at Layer.handle [as handle_request] (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:131:13)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at Route.dispatch (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
  at /Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:277:22
  at Function.process_params (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:121:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at exports.keystoneAuth (/Users/patrikholcak/dev/test/node_modules/keystone/lib/session.js:214:2)
  at Layer.handle [as handle_request] (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:131:13)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:125:14)
  at Route.dispatch (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
  at /Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:277:22
  at param (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:349:14)
  at param (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:365:14)
  at Function.process_params (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:410:3)
  at next (/Users/patrikholcak/dev/test/node_modules/keystone/node_modules/express/lib/router/index.js:271:10)
  at /Users/patrikholcak/dev/test/node_modules/keystone/node_modules/grappling-hook/index.js:198:10
  at doNTCallback0 (node.js:417:9)
  at process._tickCallback (node.js:346:13)
```

**Comment by TimothyGu** [comment]
The error is not thrown from acorn-globals…

**Comment by TimothyGu** [comment]
This seems to be the same bug as jadejs/jade#2153. Investigating.

**Comment by patrikholcak** [comment]
No, it isn’t, but appears to be caused by `acorn-globals`.

**Comment by TimothyGu** [comment]
Fixed. Thanks for reporting!

**Comment by patrikholcak** [comment]
:shipit: Superb, thanks!
