### ISSUE TITLE
Unexpected token with version 3.1.0

### ISSUE THREAD

**Issue by hungpham2411** [ForbesLindesay/acorn-globals#26]
Hi!
I get the following error and can't go on
```
SyntaxError: Unexpected token (8:1)
    at Parser.pp$4.raise (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp.unexpected (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:623:8)
    at Parser.pp$3.parseExprAtom (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:2011:10)
    at Parser.pp$3.parseExprSubscripts (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseMaybeUnary (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1840:26)
    at Parser.pp$3.parseExprOps (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseExpression (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:1722:19)
    at Parser.pp$1.parseStatement (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:777:45)
    at Parser.pp$1.parseTopLevel (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:672:23)
    at Parser.parse (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:529:15)
    at Object.parse (.........../node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:3378:37)
    at reallyParse (.........../node_modules/acorn-globals/index.js:22:16)
    at findGlobals (.........../node_modules/acorn-globals/index.js:35:11)
```
Thanks

**Comment by ForbesLindesay** [comment]
Please re-test with the, just released, version 4. If the problem still exists, please comment here with some example code that produces the above stack trace.
