### ISSUE TITLE
error when detect destructuring assignment

### ISSUE THREAD

**Issue by LongTengDao** [ForbesLindesay/acorn-globals#42]
```js
'use strict';
const detect = require('acorn-globals');
detect(`
var { ...rest } = {};
`);
```

```
    switch (node.type) {
                 ^

TypeError: Cannot read property 'type' of undefined
    at declarePattern      (acorn-globals\index.js:58:18)
    at                     (acorn-globals\index.js:64:11)
    at Array.forEach       (<anonymous>)
    at declarePattern      (acorn-globals\index.js:63:25)
    at                     (acorn-globals\index.js:97:9)
    at Array.forEach       (<anonymous>)
    at VariableDeclaration (acorn-globals\index.js:96:25)
    at c                   (acorn-globals\node_modules\acorn-walk\dist\walk.js:45:18)
    at Object.skipThrough  (acorn-globals\node_modules\acorn-walk\dist\walk.js:183:37)
    at c                   (acorn-globals\node_modules\acorn-walk\dist\walk.js:44:22)
```

And also `function f ({ ...rest }) { }`.

**Comment by ForbesLindesay** [comment]
Thanks, the fix for this is released in 4.3.1
