### ISSUE TITLE
Browserify doesn't work anymore

### ISSUE THREAD

**Issue by TimothyGu** [ForbesLindesay/acorn-globals#5]
```js
// browser.js

require('./')
```

```
timothy_gu@ubuntu-lenovo:~/jade/acorn-globals$ ./node_modules/.bin/browserify browser.js 
Error: Cannot find module './state' from '/home/timothy_gu/jade/acorn-globals/node_modules/acorn/dist'
    at /home/timothy_gu/jade/acorn-globals/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/timothy_gu/jade/acorn-globals/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/timothy_gu/jade/acorn-globals/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/timothy_gu/jade/acorn-globals/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:77:15)
```

This broke Jade: https://travis-ci.org/jadejs/jade/jobs/56260858#L114-L141

**Comment by TimothyGu** [comment]
```diff
diff --git a/index.js b/index.js
index a9ce807..6c7961d 100644
--- a/index.js
+++ b/index.js
@@ -1,6 +1,6 @@
 'use strict';
 
-var acorn = require('acorn');
+var acorn = require('acorn/src');
 var walk = require('acorn/dist/walk');
 
 // polyfill for https://github.com/marijnh/acorn/pull/231
```

This fixes it. Seems like Browserify is not taking the already-browserified `acorn/dist/acorn.js` well.

**Comment by TimothyGu** [comment]
But with the aforementioned patch the source is not babelified so it uses ES 6 features…

**Comment by TimothyGu** [comment]
Fixed a long time ago.
